[project]
name = "llamarag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "llama-index>=0.12.35",
    "pypdf>=5.4.0",
]
